language: python
sudo: required
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_PYTHON_SITEPACKAGES=1 CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - ./scripts/setup-google-sdk.sh
install:
  - gcloud config set project project-kel
before_script:
  - docker pull quay.io/kelproject/gb-build
script:
  - ./scripts/build.sh
after_success:
  - ./scripts/deploy.sh
